---
- name: Create directories for Nexus
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/nexus/
    - /tmp/nexus/
  become: yes

- name: Download Nexus
  get_url:
    url: "{{ nexus_url }}"
    dest: /opt/nexus/nexus.tar.gz
  become: yes

- name: Extract Nexus
  command: "tar xzvf /opt/nexus/nexus.tar.gz"
  become: yes
  args:
    chdir: /opt/nexus/

- name: Debug Nexus Directory
  debug:
    var: lookup('fileglob', '/opt/nexus/*')
  become: yes

- name: Add nexus user
  user:
    name: nexus
    state: present
  become: yes

- name: Change ownership of Nexus directory
  command: "chown -R nexus:nexus /opt/nexus"
  become: yes

- name: Copy Nexus systemd service
  copy:
    src: nexus.jq
    dest: /etc/systemd/system/nexus.service
  become: yes

- name: Set run_as_user in nexus.rc
  lineinfile:
    path: "/opt/nexus/{{ nexus_dir }}/bin/nexus.rc"
    line: "run_as_user=\"nexus\""
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Start Nexus service
  service:
    name: nexus
    enabled: yes
    state: started
  become: yes

